name: newbase
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9.19
  - conda==24.5.0
  - tensorflow_data_validation
  - grpcio_status
  - grpc-google-iam-v1=0.13.1
  - google_cloud_resource_manager
  - google_api_core
  - google_cloud_storage
  - fastavro=1.9.4
  - fastparquet=2024.5.0
  - gcsfs=2024.6.1
  - google-cloud-bigquery-storage=2.25.0
  - google-cloud-bigtable=2.24.0
  - google-cloud-dataproc=5.10.0
  - google-cloud-datastore=2.19.0
  - google-cloud-monitoring=2.22.0
  - google-cloud-pubsub=2.21.5
  - google-cloud-vision=3.7.2
  - numba=0.60.0
  - orc
  - regex=2024.5.15
  - scikit-image=0.24.0
  - seaborn=0.13.2
  - google-cloud-aiplatform=1.57.0
  - kfp=2.8.0
  - sqlalchemy=2.0.31
  - pandas_gbq
  - koalas=1.8.2
  - mleap=0.23.1
  - pysal
  - rtree=1.2.0
  - matplotlib
